// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaignsmodel/campaignsmodel.proto

package campaignsmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SPCampaignDTO struct {
	// `json:"campaignId,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"campaignId,omitempty"`
	// `json:"portfolioId,omitempty"`
	PortfolioID string `protobuf:"bytes,2,opt,name=PortfolioID,proto3" json:"portfolioId,omitempty"`
	// `json:"name,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name,omitempty"`
	// `json:"campaignType,omitempty"`
	CampaignType string `protobuf:"bytes,4,opt,name=CampaignType,proto3" json:"campaignType,omitempty"`
	// `json:"targetingType,omitempty"`
	TargetingType string `protobuf:"bytes,5,opt,name=TargetingType,proto3" json:"targetingType,omitempty"`
	// `json:"premiumBidAdjustment,omitempty"`
	PremiumBidAdjustment bool `protobuf:"varint,6,opt,name=PremiumBidAdjustment,proto3" json:"premiumBidAdjustment,omitempty"`
	// `json:"dailyBudget,omitempty"`
	DailyBudget float32 `protobuf:"fixed32,7,opt,name=DailyBudget,proto3" json:"dailyBudget,omitempty"`
	// `json:"startDate,omitempty"`
	StartDate string `protobuf:"bytes,8,opt,name=StartDate,proto3" json:"startDate,omitempty"`
	// `json:"endDate,omitempty"`
	EndDate string `protobuf:"bytes,9,opt,name=EndDate,proto3" json:"endDate,omitempty"`
	// `json:"state,omitempty"`
	State string `protobuf:"bytes,10,opt,name=State,proto3" json:"state,omitempty"`
	// `json:"bidding,omitempty"`
	Bidding              *BiddingDTO `protobuf:"bytes,11,opt,name=Bidding,proto3" json:"bidding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SPCampaignDTO) Reset()         { *m = SPCampaignDTO{} }
func (m *SPCampaignDTO) String() string { return proto.CompactTextString(m) }
func (*SPCampaignDTO) ProtoMessage()    {}
func (*SPCampaignDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{0}
}

func (m *SPCampaignDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPCampaignDTO.Unmarshal(m, b)
}
func (m *SPCampaignDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPCampaignDTO.Marshal(b, m, deterministic)
}
func (m *SPCampaignDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPCampaignDTO.Merge(m, src)
}
func (m *SPCampaignDTO) XXX_Size() int {
	return xxx_messageInfo_SPCampaignDTO.Size(m)
}
func (m *SPCampaignDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_SPCampaignDTO.DiscardUnknown(m)
}

var xxx_messageInfo_SPCampaignDTO proto.InternalMessageInfo

func (m *SPCampaignDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SPCampaignDTO) GetPortfolioID() string {
	if m != nil {
		return m.PortfolioID
	}
	return ""
}

func (m *SPCampaignDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SPCampaignDTO) GetCampaignType() string {
	if m != nil {
		return m.CampaignType
	}
	return ""
}

func (m *SPCampaignDTO) GetTargetingType() string {
	if m != nil {
		return m.TargetingType
	}
	return ""
}

func (m *SPCampaignDTO) GetPremiumBidAdjustment() bool {
	if m != nil {
		return m.PremiumBidAdjustment
	}
	return false
}

func (m *SPCampaignDTO) GetDailyBudget() float32 {
	if m != nil {
		return m.DailyBudget
	}
	return 0
}

func (m *SPCampaignDTO) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *SPCampaignDTO) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *SPCampaignDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SPCampaignDTO) GetBidding() *BiddingDTO {
	if m != nil {
		return m.Bidding
	}
	return nil
}

type BiddingDTO struct {
	// `json:"strategy,omitempty"`
	Strategy string `protobuf:"bytes,1,opt,name=Strategy,proto3" json:"strategy,omitempty"`
	// `json:"adjustments,omitempty"`
	Adjustments          []*AdjustmentDTO `protobuf:"bytes,2,rep,name=Adjustments,proto3" json:"adjustments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BiddingDTO) Reset()         { *m = BiddingDTO{} }
func (m *BiddingDTO) String() string { return proto.CompactTextString(m) }
func (*BiddingDTO) ProtoMessage()    {}
func (*BiddingDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{1}
}

func (m *BiddingDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiddingDTO.Unmarshal(m, b)
}
func (m *BiddingDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiddingDTO.Marshal(b, m, deterministic)
}
func (m *BiddingDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiddingDTO.Merge(m, src)
}
func (m *BiddingDTO) XXX_Size() int {
	return xxx_messageInfo_BiddingDTO.Size(m)
}
func (m *BiddingDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_BiddingDTO.DiscardUnknown(m)
}

var xxx_messageInfo_BiddingDTO proto.InternalMessageInfo

func (m *BiddingDTO) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *BiddingDTO) GetAdjustments() []*AdjustmentDTO {
	if m != nil {
		return m.Adjustments
	}
	return nil
}

type AdjustmentDTO struct {
	// `json:"predicate,omitempty"`
	Predicate string `protobuf:"bytes,1,opt,name=Predicate,proto3" json:"predicate,omitempty"`
	// `json:"percentage,omitempty"`
	Percentage           float32  `protobuf:"fixed32,2,opt,name=Percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdjustmentDTO) Reset()         { *m = AdjustmentDTO{} }
func (m *AdjustmentDTO) String() string { return proto.CompactTextString(m) }
func (*AdjustmentDTO) ProtoMessage()    {}
func (*AdjustmentDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{2}
}

func (m *AdjustmentDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjustmentDTO.Unmarshal(m, b)
}
func (m *AdjustmentDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjustmentDTO.Marshal(b, m, deterministic)
}
func (m *AdjustmentDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjustmentDTO.Merge(m, src)
}
func (m *AdjustmentDTO) XXX_Size() int {
	return xxx_messageInfo_AdjustmentDTO.Size(m)
}
func (m *AdjustmentDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjustmentDTO.DiscardUnknown(m)
}

var xxx_messageInfo_AdjustmentDTO proto.InternalMessageInfo

func (m *AdjustmentDTO) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *AdjustmentDTO) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

type SBCampaignDTO struct {
	// `json:"campaignId,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"campaignId,omitempty"`
	// `json:"portfolioId,omitempty"`
	PortfolioID string `protobuf:"bytes,2,opt,name=PortfolioID,proto3" json:"portfolioId,omitempty"`
	// `json:"name,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name,omitempty"`
	// `json:"budget,omitempty"`
	Budget float32 `protobuf:"fixed32,4,opt,name=Budget,proto3" json:"budget,omitempty"`
	// `json:"budgetType,omitempty"`
	BudgetType string `protobuf:"bytes,5,opt,name=BudgetType,proto3" json:"budgetType,omitempty"`
	// `json:"startDate,omitempty"`
	StartDate string `protobuf:"bytes,6,opt,name=StartDate,proto3" json:"startDate,omitempty"`
	// `json:"endDate,omitempty"`
	EndDate string `protobuf:"bytes,7,opt,name=EndDate,proto3" json:"endDate,omitempty"`
	// `json:"adFormat,omitempty"`
	AdFormat string `protobuf:"bytes,8,opt,name=AdFormat,proto3" json:"adFormat,omitempty"`
	// `json:"state,omitempty"`
	State string `protobuf:"bytes,9,opt,name=State,proto3" json:"state,omitempty"`
	// `json:"brandEntityId,omitempty"`
	BrandEntityID string `protobuf:"bytes,10,opt,name=BrandEntityID,proto3" json:"brandEntityId,omitempty"`
	// `json:"bidOptimization,omitempty"`
	BidOptimization bool `protobuf:"varint,11,opt,name=BidOptimization,proto3" json:"bidOptimization,omitempty"`
	// `json:"bidMultiplier,omitempty"`
	BidMultiplier int64 `protobuf:"varint,12,opt,name=BidMultiplier,proto3" json:"bidMultiplier,omitempty"`
	// `json:"servingStatus,omitempty"`
	ServingStatus string `protobuf:"bytes,13,opt,name=ServingStatus,proto3" json:"servingStatus,omitempty"`
	// `json:"creative,omitempty"`
	Creative *CreativeDTO `protobuf:"bytes,14,opt,name=Creative,proto3" json:"creative,omitempty"`
	// `json:"landingPage,omitempty"`
	LandingPage *LandingPageDTO `protobuf:"bytes,15,opt,name=LandingPage,proto3" json:"landingPage,omitempty"`
	// `json:"keywords,omitempty"`
	Keywords             []*KeywordDTO `protobuf:"bytes,16,rep,name=Keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SBCampaignDTO) Reset()         { *m = SBCampaignDTO{} }
func (m *SBCampaignDTO) String() string { return proto.CompactTextString(m) }
func (*SBCampaignDTO) ProtoMessage()    {}
func (*SBCampaignDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{3}
}

func (m *SBCampaignDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SBCampaignDTO.Unmarshal(m, b)
}
func (m *SBCampaignDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SBCampaignDTO.Marshal(b, m, deterministic)
}
func (m *SBCampaignDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SBCampaignDTO.Merge(m, src)
}
func (m *SBCampaignDTO) XXX_Size() int {
	return xxx_messageInfo_SBCampaignDTO.Size(m)
}
func (m *SBCampaignDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_SBCampaignDTO.DiscardUnknown(m)
}

var xxx_messageInfo_SBCampaignDTO proto.InternalMessageInfo

func (m *SBCampaignDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SBCampaignDTO) GetPortfolioID() string {
	if m != nil {
		return m.PortfolioID
	}
	return ""
}

func (m *SBCampaignDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SBCampaignDTO) GetBudget() float32 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func (m *SBCampaignDTO) GetBudgetType() string {
	if m != nil {
		return m.BudgetType
	}
	return ""
}

func (m *SBCampaignDTO) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *SBCampaignDTO) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *SBCampaignDTO) GetAdFormat() string {
	if m != nil {
		return m.AdFormat
	}
	return ""
}

func (m *SBCampaignDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SBCampaignDTO) GetBrandEntityID() string {
	if m != nil {
		return m.BrandEntityID
	}
	return ""
}

func (m *SBCampaignDTO) GetBidOptimization() bool {
	if m != nil {
		return m.BidOptimization
	}
	return false
}

func (m *SBCampaignDTO) GetBidMultiplier() int64 {
	if m != nil {
		return m.BidMultiplier
	}
	return 0
}

func (m *SBCampaignDTO) GetServingStatus() string {
	if m != nil {
		return m.ServingStatus
	}
	return ""
}

func (m *SBCampaignDTO) GetCreative() *CreativeDTO {
	if m != nil {
		return m.Creative
	}
	return nil
}

func (m *SBCampaignDTO) GetLandingPage() *LandingPageDTO {
	if m != nil {
		return m.LandingPage
	}
	return nil
}

func (m *SBCampaignDTO) GetKeywords() []*KeywordDTO {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type CreativeDTO struct {
	//`json:"brandName,omitempty"`
	BrandName string `protobuf:"bytes,1,opt,name=BrandName,proto3" json:"brandName,omitempty"`
	//`json:"brandLogoAssetId,omitempty"`
	BrandLogoAssetID string `protobuf:"bytes,2,opt,name=BrandLogoAssetID,proto3" json:"brandLogoAssetId,omitempty"`
	//`json:"headline,omitempty"`
	Headline string `protobuf:"bytes,3,opt,name=Headline,proto3" json:"headline,omitempty"`
	//`json:"shouldOptimizeAsins,omitempty"`
	ShouldOptimizeAsins bool `protobuf:"varint,4,opt,name=ShouldOptimizeAsins,proto3" json:"shouldOptimizeAsins,omitempty"`
	//`json:"asins,omitempty"`
	ASINs []string `protobuf:"bytes,5,rep,name=ASINs,proto3" json:"asins,omitempty"`
	//`json:"brandLogoUrl,omitempty"`
	BrandLogoURL         string   `protobuf:"bytes,6,opt,name=BrandLogoURL,proto3" json:"brandLogoUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreativeDTO) Reset()         { *m = CreativeDTO{} }
func (m *CreativeDTO) String() string { return proto.CompactTextString(m) }
func (*CreativeDTO) ProtoMessage()    {}
func (*CreativeDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{4}
}

func (m *CreativeDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreativeDTO.Unmarshal(m, b)
}
func (m *CreativeDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreativeDTO.Marshal(b, m, deterministic)
}
func (m *CreativeDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreativeDTO.Merge(m, src)
}
func (m *CreativeDTO) XXX_Size() int {
	return xxx_messageInfo_CreativeDTO.Size(m)
}
func (m *CreativeDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_CreativeDTO.DiscardUnknown(m)
}

var xxx_messageInfo_CreativeDTO proto.InternalMessageInfo

func (m *CreativeDTO) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *CreativeDTO) GetBrandLogoAssetID() string {
	if m != nil {
		return m.BrandLogoAssetID
	}
	return ""
}

func (m *CreativeDTO) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *CreativeDTO) GetShouldOptimizeAsins() bool {
	if m != nil {
		return m.ShouldOptimizeAsins
	}
	return false
}

func (m *CreativeDTO) GetASINs() []string {
	if m != nil {
		return m.ASINs
	}
	return nil
}

func (m *CreativeDTO) GetBrandLogoURL() string {
	if m != nil {
		return m.BrandLogoURL
	}
	return ""
}

type LandingPageDTO struct {
	//`json:"pageType,omitempty"`
	PageType string `protobuf:"bytes,1,opt,name=PageType,proto3" json:"pageType,omitempty"`
	//`json:"url,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL,proto3" json:"url,omitempty"`
	//`json:"asins,omitempty"`
	ASINs                []string `protobuf:"bytes,3,rep,name=ASINs,proto3" json:"asins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LandingPageDTO) Reset()         { *m = LandingPageDTO{} }
func (m *LandingPageDTO) String() string { return proto.CompactTextString(m) }
func (*LandingPageDTO) ProtoMessage()    {}
func (*LandingPageDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{5}
}

func (m *LandingPageDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LandingPageDTO.Unmarshal(m, b)
}
func (m *LandingPageDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LandingPageDTO.Marshal(b, m, deterministic)
}
func (m *LandingPageDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LandingPageDTO.Merge(m, src)
}
func (m *LandingPageDTO) XXX_Size() int {
	return xxx_messageInfo_LandingPageDTO.Size(m)
}
func (m *LandingPageDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_LandingPageDTO.DiscardUnknown(m)
}

var xxx_messageInfo_LandingPageDTO proto.InternalMessageInfo

func (m *LandingPageDTO) GetPageType() string {
	if m != nil {
		return m.PageType
	}
	return ""
}

func (m *LandingPageDTO) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *LandingPageDTO) GetASINs() []string {
	if m != nil {
		return m.ASINs
	}
	return nil
}

type BidRecommendationsDTO struct {
	//`json:"adGroupId,omitempty"`
	AdGroupID string `protobuf:"bytes,1,opt,name=AdGroupID,proto3" json:"adGroupId,omitempty"`
	//`json:"suggestedBid,omitempty"`
	SuggestedBid *SuggestedBidDTO `protobuf:"bytes,2,opt,name=SuggestedBid,proto3" json:"suggestedBid,omitempty"`
	//`json:"recommendations,omitempty"`
	Recommendations      []*RecommendationsDTO `protobuf:"bytes,3,rep,name=Recommendations,proto3" json:"recommendations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BidRecommendationsDTO) Reset()         { *m = BidRecommendationsDTO{} }
func (m *BidRecommendationsDTO) String() string { return proto.CompactTextString(m) }
func (*BidRecommendationsDTO) ProtoMessage()    {}
func (*BidRecommendationsDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{6}
}

func (m *BidRecommendationsDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidRecommendationsDTO.Unmarshal(m, b)
}
func (m *BidRecommendationsDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidRecommendationsDTO.Marshal(b, m, deterministic)
}
func (m *BidRecommendationsDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidRecommendationsDTO.Merge(m, src)
}
func (m *BidRecommendationsDTO) XXX_Size() int {
	return xxx_messageInfo_BidRecommendationsDTO.Size(m)
}
func (m *BidRecommendationsDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_BidRecommendationsDTO.DiscardUnknown(m)
}

var xxx_messageInfo_BidRecommendationsDTO proto.InternalMessageInfo

func (m *BidRecommendationsDTO) GetAdGroupID() string {
	if m != nil {
		return m.AdGroupID
	}
	return ""
}

func (m *BidRecommendationsDTO) GetSuggestedBid() *SuggestedBidDTO {
	if m != nil {
		return m.SuggestedBid
	}
	return nil
}

func (m *BidRecommendationsDTO) GetRecommendations() []*RecommendationsDTO {
	if m != nil {
		return m.Recommendations
	}
	return nil
}

type RecommendationsDTO struct {
	//`json:"code,omitempty"`
	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"code,omitempty"`
	//`json:"expression,omitempty"`
	Expression []*ExpressionDTO `protobuf:"bytes,2,rep,name=Expression,proto3" json:"expression,omitempty"`
	//`json:"suggestedBid,omitempty"`
	SuggestedBid         *SuggestedBidDTO `protobuf:"bytes,3,opt,name=SuggestedBid,proto3" json:"suggestedBid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RecommendationsDTO) Reset()         { *m = RecommendationsDTO{} }
func (m *RecommendationsDTO) String() string { return proto.CompactTextString(m) }
func (*RecommendationsDTO) ProtoMessage()    {}
func (*RecommendationsDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{7}
}

func (m *RecommendationsDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendationsDTO.Unmarshal(m, b)
}
func (m *RecommendationsDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendationsDTO.Marshal(b, m, deterministic)
}
func (m *RecommendationsDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendationsDTO.Merge(m, src)
}
func (m *RecommendationsDTO) XXX_Size() int {
	return xxx_messageInfo_RecommendationsDTO.Size(m)
}
func (m *RecommendationsDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendationsDTO.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendationsDTO proto.InternalMessageInfo

func (m *RecommendationsDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RecommendationsDTO) GetExpression() []*ExpressionDTO {
	if m != nil {
		return m.Expression
	}
	return nil
}

func (m *RecommendationsDTO) GetSuggestedBid() *SuggestedBidDTO {
	if m != nil {
		return m.SuggestedBid
	}
	return nil
}

type ExpressionDTO struct {
	//`json:"value,omitempty"`
	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"value,omitempty"`
	//`json:"type,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpressionDTO) Reset()         { *m = ExpressionDTO{} }
func (m *ExpressionDTO) String() string { return proto.CompactTextString(m) }
func (*ExpressionDTO) ProtoMessage()    {}
func (*ExpressionDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{8}
}

func (m *ExpressionDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionDTO.Unmarshal(m, b)
}
func (m *ExpressionDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionDTO.Marshal(b, m, deterministic)
}
func (m *ExpressionDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionDTO.Merge(m, src)
}
func (m *ExpressionDTO) XXX_Size() int {
	return xxx_messageInfo_ExpressionDTO.Size(m)
}
func (m *ExpressionDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionDTO proto.InternalMessageInfo

func (m *ExpressionDTO) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ExpressionDTO) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SuggestedBidDTO struct {
	//`json:"rangeEnd,omitempty"`
	RangeEnd float32 `protobuf:"fixed32,1,opt,name=RangeEnd,proto3" json:"rangeEnd,omitempty"`
	//`json:"rangeStart,omitempty"`
	RangeStart float32 `protobuf:"fixed32,2,opt,name=RangeStart,proto3" json:"rangeStart,omitempty"`
	//`json:"suggested,omitempty"`
	Suggested            float32  `protobuf:"fixed32,3,opt,name=Suggested,proto3" json:"suggested,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestedBidDTO) Reset()         { *m = SuggestedBidDTO{} }
func (m *SuggestedBidDTO) String() string { return proto.CompactTextString(m) }
func (*SuggestedBidDTO) ProtoMessage()    {}
func (*SuggestedBidDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{9}
}

func (m *SuggestedBidDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestedBidDTO.Unmarshal(m, b)
}
func (m *SuggestedBidDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestedBidDTO.Marshal(b, m, deterministic)
}
func (m *SuggestedBidDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestedBidDTO.Merge(m, src)
}
func (m *SuggestedBidDTO) XXX_Size() int {
	return xxx_messageInfo_SuggestedBidDTO.Size(m)
}
func (m *SuggestedBidDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestedBidDTO.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestedBidDTO proto.InternalMessageInfo

func (m *SuggestedBidDTO) GetRangeEnd() float32 {
	if m != nil {
		return m.RangeEnd
	}
	return 0
}

func (m *SuggestedBidDTO) GetRangeStart() float32 {
	if m != nil {
		return m.RangeStart
	}
	return 0
}

func (m *SuggestedBidDTO) GetSuggested() float32 {
	if m != nil {
		return m.Suggested
	}
	return 0
}

type AdGroupDTO struct {
	//`json:"adGroupId,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"adGroupId,omitempty"`
	//`json:"campaignId,omitempty"`
	CampaignID string `protobuf:"bytes,2,opt,name=CampaignID,proto3" json:"campaignId,omitempty"`
	//`json:"name,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name,omitempty"`
	//`json:"state,omitempty"`
	State string `protobuf:"bytes,4,opt,name=State,proto3" json:"state,omitempty"`
	//`json:"defaultBid,omitempty"`
	DefaultBid float32 `protobuf:"fixed32,5,opt,name=DefaultBid,proto3" json:"defaultBid,omitempty"`
	//`json:"bid,omitempty"`
	Bid                  float32  `protobuf:"fixed32,6,opt,name=Bid,proto3" json:"bid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdGroupDTO) Reset()         { *m = AdGroupDTO{} }
func (m *AdGroupDTO) String() string { return proto.CompactTextString(m) }
func (*AdGroupDTO) ProtoMessage()    {}
func (*AdGroupDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{10}
}

func (m *AdGroupDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdGroupDTO.Unmarshal(m, b)
}
func (m *AdGroupDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdGroupDTO.Marshal(b, m, deterministic)
}
func (m *AdGroupDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdGroupDTO.Merge(m, src)
}
func (m *AdGroupDTO) XXX_Size() int {
	return xxx_messageInfo_AdGroupDTO.Size(m)
}
func (m *AdGroupDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_AdGroupDTO.DiscardUnknown(m)
}

var xxx_messageInfo_AdGroupDTO proto.InternalMessageInfo

func (m *AdGroupDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AdGroupDTO) GetCampaignID() string {
	if m != nil {
		return m.CampaignID
	}
	return ""
}

func (m *AdGroupDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdGroupDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AdGroupDTO) GetDefaultBid() float32 {
	if m != nil {
		return m.DefaultBid
	}
	return 0
}

func (m *AdGroupDTO) GetBid() float32 {
	if m != nil {
		return m.Bid
	}
	return 0
}

type ProductAdDTO struct {
	//`json:"adId,omitempty"`
	AdID string `protobuf:"bytes,1,opt,name=AdID,proto3" json:"adId,omitempty"`
	//`json:"adGroupId,omitempty"`
	AdGroupID string `protobuf:"bytes,2,opt,name=AdGroupID,proto3" json:"adGroupId,omitempty"`
	//`json:"campaignId,omitempty"`
	CampaignID string `protobuf:"bytes,3,opt,name=CampaignID,proto3" json:"campaignId,omitempty"`
	//`json:"asin,omitempty"`
	ASIN string `protobuf:"bytes,4,opt,name=ASIN,proto3" json:"asin,omitempty"`
	//`json:"sku,omitempty"`
	SKU string `protobuf:"bytes,5,opt,name=SKU,proto3" json:"sku,omitempty"`
	//`json:"state,omitempty"`
	State                string   `protobuf:"bytes,6,opt,name=State,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductAdDTO) Reset()         { *m = ProductAdDTO{} }
func (m *ProductAdDTO) String() string { return proto.CompactTextString(m) }
func (*ProductAdDTO) ProtoMessage()    {}
func (*ProductAdDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{11}
}

func (m *ProductAdDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAdDTO.Unmarshal(m, b)
}
func (m *ProductAdDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAdDTO.Marshal(b, m, deterministic)
}
func (m *ProductAdDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAdDTO.Merge(m, src)
}
func (m *ProductAdDTO) XXX_Size() int {
	return xxx_messageInfo_ProductAdDTO.Size(m)
}
func (m *ProductAdDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAdDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAdDTO proto.InternalMessageInfo

func (m *ProductAdDTO) GetAdID() string {
	if m != nil {
		return m.AdID
	}
	return ""
}

func (m *ProductAdDTO) GetAdGroupID() string {
	if m != nil {
		return m.AdGroupID
	}
	return ""
}

func (m *ProductAdDTO) GetCampaignID() string {
	if m != nil {
		return m.CampaignID
	}
	return ""
}

func (m *ProductAdDTO) GetASIN() string {
	if m != nil {
		return m.ASIN
	}
	return ""
}

func (m *ProductAdDTO) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *ProductAdDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type KeywordDTO struct {
	//`json:"campaignId,omitempty"`
	CampaignID string `protobuf:"bytes,1,opt,name=CampaignID,proto3" json:"campaignId,omitempty"`
	//`json:"adGroupId,omitempty"`
	AdGroupID string `protobuf:"bytes,2,opt,name=AdGroupID,proto3" json:"adGroupId,omitempty"`
	//`json:"keywordId,omitempty"`
	KeywordID string `protobuf:"bytes,3,opt,name=KeywordID,proto3" json:"keywordId,omitempty"`
	//`json:"state,omitempty"`
	State string `protobuf:"bytes,4,opt,name=State,proto3" json:"state,omitempty"`
	//`json:"keywordText,omitempty"`
	KeywordText string `protobuf:"bytes,5,opt,name=KeywordText,proto3" json:"keywordText,omitempty"`
	//`json:"nativeLanguageKeyword,omitempty"`
	NativeLanguageKeyword string `protobuf:"bytes,6,opt,name=NativeLanguageKeyword,proto3" json:"nativeLanguageKeyword,omitempty"`
	//`json:"nativeLanguageLocale,omitempty"`
	NativeLanguageLocale string `protobuf:"bytes,7,opt,name=NativeLanguageLocale,proto3" json:"nativeLanguageLocale,omitempty"`
	//`json:"matchType,omitempty"`
	MatchType string `protobuf:"bytes,8,opt,name=MatchType,proto3" json:"matchType,omitempty"`
	//`json:"bid,omitempty"`
	Bid                  float32  `protobuf:"fixed32,9,opt,name=Bid,proto3" json:"bid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeywordDTO) Reset()         { *m = KeywordDTO{} }
func (m *KeywordDTO) String() string { return proto.CompactTextString(m) }
func (*KeywordDTO) ProtoMessage()    {}
func (*KeywordDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{12}
}

func (m *KeywordDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeywordDTO.Unmarshal(m, b)
}
func (m *KeywordDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeywordDTO.Marshal(b, m, deterministic)
}
func (m *KeywordDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeywordDTO.Merge(m, src)
}
func (m *KeywordDTO) XXX_Size() int {
	return xxx_messageInfo_KeywordDTO.Size(m)
}
func (m *KeywordDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_KeywordDTO.DiscardUnknown(m)
}

var xxx_messageInfo_KeywordDTO proto.InternalMessageInfo

func (m *KeywordDTO) GetCampaignID() string {
	if m != nil {
		return m.CampaignID
	}
	return ""
}

func (m *KeywordDTO) GetAdGroupID() string {
	if m != nil {
		return m.AdGroupID
	}
	return ""
}

func (m *KeywordDTO) GetKeywordID() string {
	if m != nil {
		return m.KeywordID
	}
	return ""
}

func (m *KeywordDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *KeywordDTO) GetKeywordText() string {
	if m != nil {
		return m.KeywordText
	}
	return ""
}

func (m *KeywordDTO) GetNativeLanguageKeyword() string {
	if m != nil {
		return m.NativeLanguageKeyword
	}
	return ""
}

func (m *KeywordDTO) GetNativeLanguageLocale() string {
	if m != nil {
		return m.NativeLanguageLocale
	}
	return ""
}

func (m *KeywordDTO) GetMatchType() string {
	if m != nil {
		return m.MatchType
	}
	return ""
}

func (m *KeywordDTO) GetBid() float32 {
	if m != nil {
		return m.Bid
	}
	return 0
}

type TargetDTO struct {
	//`json:"campaignId,omitempty"`
	CampaignID string `protobuf:"bytes,1,opt,name=CampaignID,proto3" json:"campaignId,omitempty"`
	//`json:"adGroupId,omitempty"`
	AdGroupID string `protobuf:"bytes,2,opt,name=AdGroupID,proto3" json:"adGroupId,omitempty"`
	//`json:"targetId,omitempty"`
	TargetID string `protobuf:"bytes,3,opt,name=TargetID,proto3" json:"targetId,omitempty"`
	//`json:"expressionType,omitempty"`
	ExpressionType string `protobuf:"bytes,4,opt,name=ExpressionType,proto3" json:"expressionType,omitempty"`
	//`json:"expression,omitempty"`
	Expression []*ExpressionDTO `protobuf:"bytes,5,rep,name=Expression,proto3" json:"expression,omitempty"`
	//`json:"bid,omitempty"`
	Bid float32 `protobuf:"fixed32,6,opt,name=Bid,proto3" json:"bid,omitempty"`
	//`json:"state,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=State,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetDTO) Reset()         { *m = TargetDTO{} }
func (m *TargetDTO) String() string { return proto.CompactTextString(m) }
func (*TargetDTO) ProtoMessage()    {}
func (*TargetDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{13}
}

func (m *TargetDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetDTO.Unmarshal(m, b)
}
func (m *TargetDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetDTO.Marshal(b, m, deterministic)
}
func (m *TargetDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetDTO.Merge(m, src)
}
func (m *TargetDTO) XXX_Size() int {
	return xxx_messageInfo_TargetDTO.Size(m)
}
func (m *TargetDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetDTO.DiscardUnknown(m)
}

var xxx_messageInfo_TargetDTO proto.InternalMessageInfo

func (m *TargetDTO) GetCampaignID() string {
	if m != nil {
		return m.CampaignID
	}
	return ""
}

func (m *TargetDTO) GetAdGroupID() string {
	if m != nil {
		return m.AdGroupID
	}
	return ""
}

func (m *TargetDTO) GetTargetID() string {
	if m != nil {
		return m.TargetID
	}
	return ""
}

func (m *TargetDTO) GetExpressionType() string {
	if m != nil {
		return m.ExpressionType
	}
	return ""
}

func (m *TargetDTO) GetExpression() []*ExpressionDTO {
	if m != nil {
		return m.Expression
	}
	return nil
}

func (m *TargetDTO) GetBid() float32 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *TargetDTO) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ResponseDTO struct {
	//`json:"campaignId,omitempty"`
	CampaignID string `protobuf:"bytes,1,opt,name=CampaignID,proto3" json:"campaignId,omitempty"`
	//`json:"adGroupId,omitempty"`
	AdGroupID string `protobuf:"bytes,2,opt,name=AdGroupID,proto3" json:"adGroupId,omitempty"`
	//`json:"assetID,omitempty"`
	AssetID string `protobuf:"bytes,3,opt,name=AssetID,proto3" json:"assetID,omitempty"`
	//`json:"code,omitempty"`
	Code string `protobuf:"bytes,4,opt,name=Code,proto3" json:"code,omitempty"`
	//`json:"description,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=Description,proto3" json:"description,omitempty"`
	//`json:"details,omitempty"`
	Details              string   `protobuf:"bytes,6,opt,name=Details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseDTO) Reset()         { *m = ResponseDTO{} }
func (m *ResponseDTO) String() string { return proto.CompactTextString(m) }
func (*ResponseDTO) ProtoMessage()    {}
func (*ResponseDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{14}
}

func (m *ResponseDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDTO.Unmarshal(m, b)
}
func (m *ResponseDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDTO.Marshal(b, m, deterministic)
}
func (m *ResponseDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDTO.Merge(m, src)
}
func (m *ResponseDTO) XXX_Size() int {
	return xxx_messageInfo_ResponseDTO.Size(m)
}
func (m *ResponseDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDTO.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDTO proto.InternalMessageInfo

func (m *ResponseDTO) GetCampaignID() string {
	if m != nil {
		return m.CampaignID
	}
	return ""
}

func (m *ResponseDTO) GetAdGroupID() string {
	if m != nil {
		return m.AdGroupID
	}
	return ""
}

func (m *ResponseDTO) GetAssetID() string {
	if m != nil {
		return m.AssetID
	}
	return ""
}

func (m *ResponseDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResponseDTO) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResponseDTO) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type BrandDTO struct {
	//`json:"brandId,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"brandId,omitempty"`
	//`json:"brandEntityId,omitempty"`
	EntityId string `protobuf:"bytes,2,opt,name=EntityId,proto3" json:"brandEntityId,omitempty"`
	//`json:"brandRegistryName,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"brandRegistryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrandDTO) Reset()         { *m = BrandDTO{} }
func (m *BrandDTO) String() string { return proto.CompactTextString(m) }
func (*BrandDTO) ProtoMessage()    {}
func (*BrandDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{15}
}

func (m *BrandDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrandDTO.Unmarshal(m, b)
}
func (m *BrandDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrandDTO.Marshal(b, m, deterministic)
}
func (m *BrandDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrandDTO.Merge(m, src)
}
func (m *BrandDTO) XXX_Size() int {
	return xxx_messageInfo_BrandDTO.Size(m)
}
func (m *BrandDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_BrandDTO.DiscardUnknown(m)
}

var xxx_messageInfo_BrandDTO proto.InternalMessageInfo

func (m *BrandDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *BrandDTO) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *BrandDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StoreDTO struct {
	//`json:"entityId,omitempty"`
	EntityId string `protobuf:"bytes,1,opt,name=EntityId,proto3" json:"entityId,omitempty"`
	//`json:"storeName,omitempty"`
	StoreName string `protobuf:"bytes,2,opt,name=StoreName,proto3" json:"storeName,omitempty"`
	//`json:"storePageInfo,omitempty"`
	Pages []*StorePageInfoDTO `protobuf:"bytes,3,rep,name=Pages,proto3" json:"storePageInfo,omitempty"`
	//`json:"brandEntityId,omitempty"`
	BrandEntityID        string   `protobuf:"bytes,4,opt,name=BrandEntityID,proto3" json:"brandEntityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreDTO) Reset()         { *m = StoreDTO{} }
func (m *StoreDTO) String() string { return proto.CompactTextString(m) }
func (*StoreDTO) ProtoMessage()    {}
func (*StoreDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{16}
}

func (m *StoreDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreDTO.Unmarshal(m, b)
}
func (m *StoreDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreDTO.Marshal(b, m, deterministic)
}
func (m *StoreDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreDTO.Merge(m, src)
}
func (m *StoreDTO) XXX_Size() int {
	return xxx_messageInfo_StoreDTO.Size(m)
}
func (m *StoreDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreDTO.DiscardUnknown(m)
}

var xxx_messageInfo_StoreDTO proto.InternalMessageInfo

func (m *StoreDTO) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *StoreDTO) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *StoreDTO) GetPages() []*StorePageInfoDTO {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *StoreDTO) GetBrandEntityID() string {
	if m != nil {
		return m.BrandEntityID
	}
	return ""
}

type StorePageInfoDTO struct {
	//`json:"storePageId,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"storePageId,omitempty"`
	//`json:"storePageUrl,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL,proto3" json:"storePageUrl,omitempty"`
	//`json:"storePageName,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"storePageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePageInfoDTO) Reset()         { *m = StorePageInfoDTO{} }
func (m *StorePageInfoDTO) String() string { return proto.CompactTextString(m) }
func (*StorePageInfoDTO) ProtoMessage()    {}
func (*StorePageInfoDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{17}
}

func (m *StorePageInfoDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePageInfoDTO.Unmarshal(m, b)
}
func (m *StorePageInfoDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePageInfoDTO.Marshal(b, m, deterministic)
}
func (m *StorePageInfoDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePageInfoDTO.Merge(m, src)
}
func (m *StorePageInfoDTO) XXX_Size() int {
	return xxx_messageInfo_StorePageInfoDTO.Size(m)
}
func (m *StorePageInfoDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePageInfoDTO.DiscardUnknown(m)
}

var xxx_messageInfo_StorePageInfoDTO proto.InternalMessageInfo

func (m *StorePageInfoDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *StorePageInfoDTO) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *StorePageInfoDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StoreAssetDTO struct {
	//`json:"assetID,omitempty"`
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"assetID,omitempty"`
	//`json:"url,omitempty"`
	URL string `protobuf:"bytes,2,opt,name=URL,proto3" json:"url,omitempty"`
	//`json:"mediaType,omitempty"`
	MediaType string `protobuf:"bytes,3,opt,name=MediaType,proto3" json:"mediaType,omitempty"`
	//`json:"name,omitempty"`
	Name string `protobuf:"bytes,4,opt,name=Name,proto3" json:"name,omitempty"`
	//`json:"brandEntityId,omitempty"`
	BrandEntityId        string   `protobuf:"bytes,5,opt,name=BrandEntityId,proto3" json:"brandEntityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreAssetDTO) Reset()         { *m = StoreAssetDTO{} }
func (m *StoreAssetDTO) String() string { return proto.CompactTextString(m) }
func (*StoreAssetDTO) ProtoMessage()    {}
func (*StoreAssetDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{18}
}

func (m *StoreAssetDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreAssetDTO.Unmarshal(m, b)
}
func (m *StoreAssetDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreAssetDTO.Marshal(b, m, deterministic)
}
func (m *StoreAssetDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreAssetDTO.Merge(m, src)
}
func (m *StoreAssetDTO) XXX_Size() int {
	return xxx_messageInfo_StoreAssetDTO.Size(m)
}
func (m *StoreAssetDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreAssetDTO.DiscardUnknown(m)
}

var xxx_messageInfo_StoreAssetDTO proto.InternalMessageInfo

func (m *StoreAssetDTO) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *StoreAssetDTO) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *StoreAssetDTO) GetMediaType() string {
	if m != nil {
		return m.MediaType
	}
	return ""
}

func (m *StoreAssetDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreAssetDTO) GetBrandEntityId() string {
	if m != nil {
		return m.BrandEntityId
	}
	return ""
}

type CreateStoreAssetCommand struct {
	ImageName string `protobuf:"bytes,1,opt,name=ImageName,proto3" json:"ImageName,omitempty"`
	ImageType string `protobuf:"bytes,2,opt,name=ImageType,proto3" json:"ImageType,omitempty"`
	//`json:"assetInfo,omitempty"`
	AssetInfo *StoreAssetDTO `protobuf:"bytes,3,opt,name=AssetInfo,proto3" json:"assetInfo,omitempty"`
	//`json:"asset,omitempty"`
	Asset                string   `protobuf:"bytes,4,opt,name=Asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreAssetCommand) Reset()         { *m = CreateStoreAssetCommand{} }
func (m *CreateStoreAssetCommand) String() string { return proto.CompactTextString(m) }
func (*CreateStoreAssetCommand) ProtoMessage()    {}
func (*CreateStoreAssetCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{19}
}

func (m *CreateStoreAssetCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreAssetCommand.Unmarshal(m, b)
}
func (m *CreateStoreAssetCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreAssetCommand.Marshal(b, m, deterministic)
}
func (m *CreateStoreAssetCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreAssetCommand.Merge(m, src)
}
func (m *CreateStoreAssetCommand) XXX_Size() int {
	return xxx_messageInfo_CreateStoreAssetCommand.Size(m)
}
func (m *CreateStoreAssetCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreAssetCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreAssetCommand proto.InternalMessageInfo

func (m *CreateStoreAssetCommand) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *CreateStoreAssetCommand) GetImageType() string {
	if m != nil {
		return m.ImageType
	}
	return ""
}

func (m *CreateStoreAssetCommand) GetAssetInfo() *StoreAssetDTO {
	if m != nil {
		return m.AssetInfo
	}
	return nil
}

func (m *CreateStoreAssetCommand) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type LandingPageASINDTO struct {
	//`json:"asinList,omitempty"`
	ASINList []string `protobuf:"bytes,1,rep,name=ASINList,proto3" json:"asinList,omitempty"`
	//`json:"code,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	//`json:"details,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=Details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LandingPageASINDTO) Reset()         { *m = LandingPageASINDTO{} }
func (m *LandingPageASINDTO) String() string { return proto.CompactTextString(m) }
func (*LandingPageASINDTO) ProtoMessage()    {}
func (*LandingPageASINDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe20d52a0da76480, []int{20}
}

func (m *LandingPageASINDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LandingPageASINDTO.Unmarshal(m, b)
}
func (m *LandingPageASINDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LandingPageASINDTO.Marshal(b, m, deterministic)
}
func (m *LandingPageASINDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LandingPageASINDTO.Merge(m, src)
}
func (m *LandingPageASINDTO) XXX_Size() int {
	return xxx_messageInfo_LandingPageASINDTO.Size(m)
}
func (m *LandingPageASINDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_LandingPageASINDTO.DiscardUnknown(m)
}

var xxx_messageInfo_LandingPageASINDTO proto.InternalMessageInfo

func (m *LandingPageASINDTO) GetASINList() []string {
	if m != nil {
		return m.ASINList
	}
	return nil
}

func (m *LandingPageASINDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LandingPageASINDTO) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*SPCampaignDTO)(nil), "campaignsmodel.SPCampaignDTO")
	proto.RegisterType((*BiddingDTO)(nil), "campaignsmodel.BiddingDTO")
	proto.RegisterType((*AdjustmentDTO)(nil), "campaignsmodel.AdjustmentDTO")
	proto.RegisterType((*SBCampaignDTO)(nil), "campaignsmodel.SBCampaignDTO")
	proto.RegisterType((*CreativeDTO)(nil), "campaignsmodel.CreativeDTO")
	proto.RegisterType((*LandingPageDTO)(nil), "campaignsmodel.LandingPageDTO")
	proto.RegisterType((*BidRecommendationsDTO)(nil), "campaignsmodel.BidRecommendationsDTO")
	proto.RegisterType((*RecommendationsDTO)(nil), "campaignsmodel.RecommendationsDTO")
	proto.RegisterType((*ExpressionDTO)(nil), "campaignsmodel.ExpressionDTO")
	proto.RegisterType((*SuggestedBidDTO)(nil), "campaignsmodel.SuggestedBidDTO")
	proto.RegisterType((*AdGroupDTO)(nil), "campaignsmodel.AdGroupDTO")
	proto.RegisterType((*ProductAdDTO)(nil), "campaignsmodel.ProductAdDTO")
	proto.RegisterType((*KeywordDTO)(nil), "campaignsmodel.KeywordDTO")
	proto.RegisterType((*TargetDTO)(nil), "campaignsmodel.TargetDTO")
	proto.RegisterType((*ResponseDTO)(nil), "campaignsmodel.ResponseDTO")
	proto.RegisterType((*BrandDTO)(nil), "campaignsmodel.BrandDTO")
	proto.RegisterType((*StoreDTO)(nil), "campaignsmodel.StoreDTO")
	proto.RegisterType((*StorePageInfoDTO)(nil), "campaignsmodel.StorePageInfoDTO")
	proto.RegisterType((*StoreAssetDTO)(nil), "campaignsmodel.StoreAssetDTO")
	proto.RegisterType((*CreateStoreAssetCommand)(nil), "campaignsmodel.CreateStoreAssetCommand")
	proto.RegisterType((*LandingPageASINDTO)(nil), "campaignsmodel.LandingPageASINDTO")
}

func init() {
	proto.RegisterFile("campaignsmodel/campaignsmodel.proto", fileDescriptor_fe20d52a0da76480)
}

var fileDescriptor_fe20d52a0da76480 = []byte{
	// 1365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xc1, 0x8e, 0xdc, 0x44,
	0x13, 0x96, 0x67, 0x66, 0x77, 0x67, 0x6a, 0x76, 0x76, 0x57, 0xfd, 0x27, 0x3f, 0xd6, 0x92, 0x2c,
	0x23, 0x13, 0xa1, 0x11, 0x87, 0x2c, 0x5a, 0xa2, 0x20, 0x84, 0x10, 0xcc, 0xec, 0x2c, 0x64, 0xc8,
	0x24, 0x19, 0x79, 0x36, 0x1c, 0x38, 0x20, 0x75, 0xdc, 0xbd, 0x4e, 0xc3, 0xd8, 0x1e, 0xd9, 0xed,
	0x25, 0x9b, 0x37, 0xe0, 0x0d, 0x38, 0x70, 0xe2, 0xc4, 0x81, 0x2b, 0x17, 0x1e, 0x00, 0xf1, 0x16,
	0xbc, 0x04, 0x17, 0x6e, 0xa8, 0xcb, 0x6d, 0xbb, 0xed, 0x71, 0x22, 0x20, 0xdc, 0xba, 0xbe, 0xaa,
	0xee, 0xaa, 0xea, 0xfa, 0x5c, 0x5d, 0x86, 0x37, 0x3d, 0x1a, 0xac, 0xa9, 0xf0, 0xc3, 0x24, 0x88,
	0x18, 0x5f, 0x1d, 0x57, 0xc5, 0xdb, 0xeb, 0x38, 0x92, 0x11, 0xd9, 0xab, 0xa2, 0xce, 0x9f, 0x2d,
	0x18, 0x2c, 0x17, 0xa7, 0x1a, 0x9c, 0x9e, 0x3f, 0x22, 0x7b, 0xd0, 0x9a, 0x4d, 0x6d, 0x6b, 0x68,
	0x8d, 0x7a, 0x6e, 0x6b, 0x36, 0x25, 0x43, 0xe8, 0x2f, 0xa2, 0x58, 0x5e, 0x44, 0x2b, 0x11, 0xcd,
	0xa6, 0x76, 0x0b, 0x15, 0x26, 0x44, 0x08, 0x74, 0x1e, 0xd2, 0x80, 0xdb, 0x6d, 0x54, 0xe1, 0x9a,
	0x38, 0xb0, 0x9b, 0x1f, 0x7a, 0x7e, 0xb5, 0xe6, 0x76, 0x07, 0x75, 0x15, 0x8c, 0xdc, 0x82, 0xc1,
	0x39, 0x8d, 0x7d, 0x2e, 0x45, 0xe8, 0xa3, 0xd1, 0x16, 0x1a, 0x55, 0x41, 0x72, 0x02, 0xd7, 0x16,
	0x31, 0x0f, 0x44, 0x1a, 0x4c, 0x04, 0x1b, 0xb3, 0xaf, 0xd2, 0x44, 0x06, 0x3c, 0x94, 0xf6, 0xf6,
	0xd0, 0x1a, 0x75, 0xdd, 0x46, 0x9d, 0x8a, 0x79, 0x4a, 0xc5, 0xea, 0x6a, 0x92, 0x32, 0x9f, 0x4b,
	0x7b, 0x67, 0x68, 0x8d, 0x5a, 0xae, 0x09, 0x91, 0x1b, 0xd0, 0x5b, 0x4a, 0x1a, 0xcb, 0x29, 0x95,
	0xdc, 0xee, 0xa2, 0xdf, 0x12, 0x20, 0x36, 0xec, 0x9c, 0x85, 0x0c, 0x75, 0x3d, 0xd4, 0xe5, 0x22,
	0xb9, 0x06, 0x5b, 0x4b, 0xa9, 0x70, 0x40, 0x3c, 0x13, 0xc8, 0x1d, 0xd8, 0x99, 0x08, 0xc6, 0x44,
	0xe8, 0xdb, 0xfd, 0xa1, 0x35, 0xea, 0x9f, 0x1c, 0xde, 0xae, 0xdd, 0xbe, 0x56, 0x4f, 0xcf, 0x1f,
	0xb9, 0xb9, 0xa9, 0x23, 0x00, 0x4a, 0x98, 0x1c, 0x42, 0x77, 0x29, 0x63, 0x2a, 0xb9, 0x7f, 0xa5,
	0x6f, 0xbf, 0x90, 0xc9, 0x47, 0xd0, 0x2f, 0xb3, 0x4b, 0xec, 0xd6, 0xb0, 0x3d, 0xea, 0x9f, 0xdc,
	0xac, 0xfb, 0x28, 0x4d, 0x94, 0x1b, 0x73, 0x87, 0xf3, 0x00, 0x06, 0x15, 0xad, 0xca, 0x7f, 0x11,
	0x73, 0x26, 0x3c, 0x95, 0x4b, 0xe6, 0xae, 0x04, 0xc8, 0x11, 0xc0, 0x82, 0xc7, 0x1e, 0x0f, 0x25,
	0xf5, 0x39, 0x96, 0xbc, 0xe5, 0x1a, 0x88, 0xf3, 0x6b, 0x07, 0x06, 0xcb, 0xc9, 0x7f, 0xcf, 0x9a,
	0xff, 0xc3, 0xb6, 0x2e, 0x59, 0x07, 0x7d, 0x6a, 0x49, 0xc5, 0x93, 0xad, 0x0c, 0x9a, 0x18, 0x48,
	0xb5, 0x9a, 0xdb, 0x2f, 0xa9, 0xe6, 0x4e, 0xb5, 0x9a, 0x87, 0xd0, 0x1d, 0xb3, 0x4f, 0xa2, 0x38,
	0xa0, 0x52, 0x93, 0xa0, 0x90, 0xcb, 0x4a, 0xf7, 0xcc, 0x4a, 0xdf, 0x82, 0xc1, 0x24, 0xa6, 0x21,
	0x3b, 0x0b, 0xa5, 0x90, 0x57, 0xb3, 0xa9, 0xe6, 0x41, 0x15, 0x24, 0x23, 0xd8, 0x9f, 0x08, 0xf6,
	0x68, 0x2d, 0x45, 0x20, 0x9e, 0x53, 0x29, 0xa2, 0x10, 0x79, 0xd1, 0x75, 0xeb, 0x30, 0x9e, 0x27,
	0xd8, 0x83, 0x74, 0x25, 0xc5, 0x7a, 0x25, 0x78, 0x6c, 0xef, 0x0e, 0xad, 0x51, 0xdb, 0xad, 0x82,
	0xca, 0x6a, 0xc9, 0xe3, 0x4b, 0x11, 0xfa, 0x2a, 0x8a, 0x34, 0xb1, 0x07, 0x99, 0xd7, 0x0a, 0x48,
	0xde, 0x83, 0xee, 0x69, 0xcc, 0xa9, 0x14, 0x97, 0xdc, 0xde, 0x43, 0x1a, 0xbe, 0x5e, 0xa7, 0x48,
	0xae, 0x57, 0x04, 0x29, 0x8c, 0xc9, 0xc7, 0xd0, 0x9f, 0xd3, 0x50, 0x11, 0x71, 0xa1, 0xea, 0xbd,
	0x8f, 0x7b, 0x8f, 0xea, 0x7b, 0x0d, 0x13, 0xe4, 0x97, 0x21, 0x93, 0xbb, 0xd0, 0xbd, 0xcf, 0xaf,
	0xbe, 0x89, 0x62, 0x96, 0xd8, 0x07, 0xc8, 0xce, 0x8d, 0x2f, 0x40, 0xeb, 0xd1, 0x73, 0x6e, 0xeb,
	0xfc, 0x6e, 0x41, 0xdf, 0x88, 0x49, 0x15, 0x12, 0x6f, 0x12, 0x99, 0xa1, 0x69, 0x59, 0x00, 0xe4,
	0x6d, 0x38, 0x40, 0x61, 0x1e, 0xf9, 0xd1, 0x38, 0x49, 0xb8, 0x2c, 0x98, 0xb5, 0x81, 0xab, 0xd2,
	0xde, 0xe3, 0x94, 0xad, 0x44, 0x98, 0x53, 0xac, 0x90, 0xc9, 0x3b, 0xf0, 0xbf, 0xe5, 0xd3, 0x28,
	0x5d, 0xe5, 0xa5, 0xe0, 0xe3, 0x44, 0x84, 0x09, 0x72, 0xae, 0xeb, 0x36, 0xa9, 0x14, 0x19, 0xc6,
	0xcb, 0xd9, 0xc3, 0xc4, 0xde, 0x1a, 0xb6, 0x15, 0x19, 0x50, 0x50, 0x4d, 0xae, 0xf0, 0xfb, 0xd8,
	0x9d, 0x6b, 0xe6, 0x55, 0x30, 0xe7, 0x1c, 0xf6, 0xaa, 0x17, 0xa7, 0x22, 0x53, 0x4b, 0xa4, 0xb2,
	0xfe, 0xd0, 0x73, 0x99, 0x1c, 0x40, 0x5b, 0x1d, 0x94, 0x25, 0xa5, 0x96, 0xa5, 0xe7, 0xb6, 0xe1,
	0xd9, 0xf9, 0xcd, 0x82, 0xeb, 0x13, 0xc1, 0x5c, 0xee, 0x45, 0x41, 0xc0, 0x43, 0x86, 0x64, 0x4a,
	0xf4, 0x0d, 0x8e, 0xd9, 0xa7, 0x71, 0x94, 0xae, 0x8b, 0xef, 0xb1, 0x04, 0xc8, 0x29, 0xec, 0x2e,
	0x53, 0xdf, 0xe7, 0x89, 0xe4, 0x6c, 0x22, 0x18, 0x3a, 0xea, 0x9f, 0xbc, 0x51, 0xaf, 0x95, 0x69,
	0xa3, 0x0a, 0x56, 0xd9, 0x44, 0xe6, 0xb0, 0x5f, 0x73, 0x8c, 0xc1, 0xf5, 0x4f, 0x9c, 0xfa, 0x39,
	0x9b, 0xf1, 0xb9, 0xf5, 0xad, 0xce, 0x4f, 0x16, 0x90, 0x86, 0x3c, 0x08, 0x74, 0x4e, 0x23, 0x96,
	0xdf, 0x10, 0xae, 0xc9, 0x87, 0x00, 0x67, 0xcf, 0xd6, 0x31, 0x4f, 0x12, 0xf5, 0x45, 0xbd, 0xa0,
	0x0b, 0x96, 0x16, 0xca, 0x9d, 0xb1, 0x61, 0x23, 0xf9, 0xf6, 0xbf, 0x48, 0xde, 0x79, 0x1f, 0x06,
	0x15, 0x0f, 0xaa, 0x40, 0x9f, 0xd3, 0x55, 0x9a, 0x47, 0x9a, 0x09, 0x2a, 0x7c, 0x2c, 0x70, 0x56,
	0x49, 0x5c, 0x3b, 0x5f, 0xc3, 0x7e, 0xed, 0x6c, 0xc5, 0x05, 0x97, 0x86, 0x3e, 0x3f, 0x0b, 0x19,
	0xee, 0x6f, 0xb9, 0x85, 0xac, 0x9a, 0x1e, 0xae, 0xb1, 0x91, 0xe5, 0x4d, 0xb8, 0x44, 0xb0, 0xe9,
	0xe5, 0xc7, 0x61, 0x2e, 0x2d, 0xb7, 0x04, 0x9c, 0xef, 0x2c, 0x00, 0x5d, 0xf7, 0xa6, 0xfe, 0x7c,
	0x04, 0x90, 0xb7, 0xef, 0xe2, 0x23, 0x32, 0x90, 0xc6, 0xee, 0x5c, 0x74, 0xc4, 0x8e, 0xd9, 0x11,
	0x8f, 0x00, 0xa6, 0xfc, 0x82, 0xa6, 0x2b, 0xa9, 0xee, 0x74, 0x2b, 0x0b, 0xb3, 0x44, 0x14, 0xa5,
	0x95, 0x62, 0x1b, 0x15, 0x6a, 0xe9, 0x7c, 0x6f, 0xc1, 0xee, 0x22, 0x8e, 0x58, 0xea, 0xc9, 0x31,
	0xd3, 0xb5, 0x1e, 0xb3, 0x22, 0x3c, 0x5c, 0x57, 0x79, 0xdc, 0xaa, 0xf3, 0xb8, 0x1a, 0x7e, 0xbb,
	0x29, 0x7c, 0xf5, 0xa1, 0xe8, 0x48, 0x71, 0xad, 0x02, 0x59, 0xde, 0x7f, 0xac, 0x5f, 0x0f, 0xb5,
	0x2c, 0x13, 0xda, 0x36, 0x12, 0x72, 0x7e, 0x69, 0x01, 0x94, 0xcd, 0xaa, 0xe6, 0xca, 0xda, 0x70,
	0xf5, 0xf2, 0x40, 0x6f, 0x40, 0x4f, 0x9f, 0x55, 0xc4, 0x59, 0x02, 0x2f, 0xb8, 0xd1, 0x21, 0xf4,
	0xb5, 0xc9, 0x39, 0x7f, 0x26, 0x75, 0xc0, 0x26, 0x44, 0xee, 0xc0, 0xf5, 0x87, 0xd8, 0x33, 0xe7,
	0x34, 0xf4, 0x53, 0xea, 0x73, 0xad, 0xd4, 0x89, 0x34, 0x2b, 0xd5, 0x24, 0x55, 0x55, 0xcc, 0x23,
	0x8f, 0xae, 0xf2, 0x47, 0xb1, 0x51, 0xa7, 0xe2, 0x7f, 0x40, 0xa5, 0xf7, 0x14, 0xc9, 0xac, 0xe7,
	0xa4, 0x02, 0xc8, 0x6b, 0xdb, 0x2b, 0x6b, 0xfb, 0x87, 0x05, 0xbd, 0x6c, 0x7e, 0x7b, 0xf5, 0xbb,
	0x3b, 0x84, 0x6e, 0x76, 0x54, 0x71, 0x75, 0x85, 0x4c, 0xde, 0x82, 0xbd, 0xf2, 0x33, 0x34, 0x26,
	0xcc, 0x1a, 0x5a, 0x6b, 0x19, 0x5b, 0xff, 0xb4, 0x65, 0x6c, 0x90, 0xb7, 0x2c, 0xd9, 0x8e, 0xc9,
	0x99, 0x9f, 0x2d, 0xe8, 0xbb, 0x3c, 0x59, 0x47, 0x61, 0xc2, 0x5f, 0x3d, 0x71, 0x1b, 0x76, 0xf2,
	0xe7, 0x2d, 0xcb, 0x3b, 0x17, 0x8b, 0xae, 0xd8, 0x31, 0xba, 0xa2, 0x1a, 0x76, 0x79, 0xe2, 0xc5,
	0x62, 0x2d, 0xb3, 0x1c, 0x91, 0x2e, 0x06, 0xa4, 0xce, 0x9b, 0x72, 0x49, 0xc5, 0x2a, 0xd1, 0x04,
	0xc9, 0x45, 0xe7, 0x33, 0xe8, 0xe2, 0x6b, 0xd5, 0xd4, 0x22, 0x0e, 0xa1, 0xab, 0x07, 0x1a, 0xa6,
	0x43, 0x2c, 0xe4, 0xa6, 0xf6, 0xe0, 0xfc, 0x60, 0xa9, 0x09, 0x36, 0x8a, 0xf3, 0x47, 0xae, 0xd8,
	0x6c, 0xd5, 0x36, 0xe3, 0xb4, 0x16, 0xc5, 0x1c, 0x4f, 0x68, 0xe5, 0xd3, 0x9a, 0x06, 0xc8, 0x5d,
	0xd8, 0x52, 0xcf, 0x61, 0xfe, 0xa6, 0x0c, 0x37, 0xda, 0xb3, 0xb2, 0x54, 0x16, 0xb3, 0xf0, 0x22,
	0x52, 0xf5, 0xca, 0xcc, 0x37, 0x27, 0xb3, 0x4e, 0xc3, 0x64, 0xe6, 0xdc, 0x83, 0x83, 0xfa, 0x01,
	0x1b, 0x89, 0x6f, 0x3e, 0xc2, 0x4d, 0xe9, 0x7e, 0x6b, 0xc1, 0x00, 0x8f, 0xc2, 0xda, 0xfc, 0xbd,
	0x73, 0xd4, 0xd7, 0xc4, 0x99, 0xa0, 0x48, 0x58, 0xdd, 0x0d, 0x0a, 0xa0, 0xf0, 0xd2, 0x31, 0x7a,
	0x6e, 0x2d, 0x2b, 0x96, 0xff, 0x23, 0x55, 0x40, 0xe7, 0x47, 0x0b, 0x5e, 0xc3, 0x31, 0x8a, 0x97,
	0x11, 0x9d, 0x46, 0x41, 0x40, 0x43, 0xbc, 0xed, 0x59, 0x40, 0x7d, 0x6e, 0x8e, 0x54, 0x05, 0x50,
	0x68, 0x8d, 0xc7, 0xaa, 0x04, 0xc8, 0x07, 0xd0, 0xcb, 0x98, 0x17, 0x5e, 0x44, 0xfa, 0xb9, 0xbc,
	0xd9, 0x58, 0x8f, 0xfc, 0x0e, 0xdc, 0xd2, 0x1e, 0x27, 0x17, 0x25, 0xe4, 0xcd, 0x0d, 0x05, 0xe7,
	0x4b, 0x20, 0xc6, 0x3c, 0xa4, 0x1a, 0xb3, 0xa6, 0x8b, 0x5a, 0xce, 0x45, 0x22, 0x6d, 0x0b, 0x07,
	0x9d, 0x42, 0x56, 0xd7, 0xe2, 0x29, 0xce, 0xeb, 0xa7, 0x54, 0xad, 0x4d, 0x46, 0xb7, 0x2b, 0x8c,
	0x9e, 0xdc, 0xf9, 0xe2, 0xc4, 0x17, 0xf2, 0x69, 0xfa, 0xe4, 0xb6, 0x17, 0x05, 0xc7, 0xc9, 0x55,
	0xe8, 0x5d, 0xa4, 0x32, 0x8d, 0xf9, 0x31, 0x0d, 0x9e, 0x53, 0x76, 0x79, 0x8c, 0xbf, 0xc1, 0x5e,
	0xed, 0xe7, 0xf8, 0xc9, 0x36, 0xc2, 0xef, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xc2, 0x18,
	0x7a, 0x44, 0x0f, 0x00, 0x00,
}
